"""
Tests for canonicalize_contraction_graph.

Three layers:
  Layer 1 – Regression: contracted expressions must exactly match .ref files
             generated by the reference implementation.
  Layer 2 – Invariants: properties that must hold regardless of implementation.
  Layer 3 – Canon-vs-no-canon consistency: every term produced without graph
             canonicalization must be accounted for in the canonical result.

Run with:
    pytest tests/diag/test_canonicalize_graph.py -v
"""

import collections
from pathlib import Path

import pytest
import wickd as w

THIS_DIR = Path(__file__).resolve().parent


# ── helpers ───────────────────────────────────────────────────────────────────

def load_ref(name: str) -> w.Expression:
    path = THIS_DIR / f"canon_{name}.ref"
    return w.utils.string_to_expr(path.read_text())


def contract(expr, *, canon: bool = True) -> w.Expression:
    wt = w.WickTheorem()
    wt.set_single_threaded(True)
    if not canon:
        wt.do_canonicalize_graph(False)
    return wt.contract(w.rational(1), expr, 0, 999)


def setup_ov():
    w.reset_space()
    w.add_space("o", "fermion", "occupied",   ["i", "j", "k", "l", "m", "n"])
    w.add_space("v", "fermion", "unoccupied", ["a", "b", "c", "d", "e", "f"])


def setup_cav():
    w.reset_space()
    w.add_space("c", "fermion", "occupied",   ["i", "j", "k", "l", "m", "n"])
    w.add_space("a", "fermion", "general",    ["u", "v", "w", "x", "y", "z"])
    w.add_space("v", "fermion", "unoccupied", ["a", "b", "c", "d", "e", "f"])


def setup_cabv():
    w.reset_space()
    w.add_space("c", "fermion", "occupied",   ["i", "j", "k", "l", "m", "n"])
    w.add_space("a", "fermion", "general",    ["u", "v", "w", "x", "y", "z"])
    w.add_space("b", "fermion", "general",    ["p", "q", "r", "s", "t", "U"])
    w.add_space("v", "fermion", "unoccupied", ["a", "b", "c", "d", "e", "f"])


# ── Layer 1: regression against reference expressions ─────────────────────────

class TestRegressionOV:
    """Two-space (occupied/virtual) — includes three- and four-body operators."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_ov()
        self.F  = w.utils.gen_op("f", 1, "ov", "ov")
        self.V  = w.utils.gen_op("v", 2, "ov", "ov")
        self.W  = w.utils.gen_op("w", 3, "ov", "ov")
        self.T1 = w.op("t", ["v+ o"])
        self.T2 = w.op("t", ["v+ v+ o o"])
        self.T3 = w.op("t", ["v+ v+ v+ o o o"])
        self.T4 = w.op("t", ["v+ v+ v+ v+ o o o o"])

    def _check(self, name, expr):
        assert contract(expr) == load_ref(name)

    def test_F_T4(self):        self._check("ov_F_T4",       self.F@self.T4)
    def test_V_T4(self):        self._check("ov_V_T4",       self.V@self.T4)
    def test_W_T4(self):        self._check("ov_W_T4",       self.W@self.T4)
    def test_V_T3_T3(self):     self._check("ov_V_T3_T3",    self.V@self.T3@self.T3)
    def test_V_T4_T4(self):     self._check("ov_V_T4_T4",    self.V@self.T4@self.T4)
    def test_V_T4_T1(self):     self._check("ov_V_T4_T1",    self.V@self.T4@self.T1)
    def test_V_T4_T2(self):     self._check("ov_V_T4_T2",    self.V@self.T4@self.T2)
    def test_W_T4_T1(self):     self._check("ov_W_T4_T1",    self.W@self.T4@self.T1)
    def test_V_T3_T3_T1(self):  self._check("ov_V_T3_T3_T1", self.V@self.T3@self.T3@self.T1)
    def test_V_T4_T1_T1(self):  self._check("ov_V_T4_T1_T1", self.V@self.T4@self.T1@self.T1)
    def test_V_T4_T2_T1(self):  self._check("ov_V_T4_T2_T1", self.V@self.T4@self.T2@self.T1)


class TestRegressionCAV:
    """Three-space (core/active/virtual) — general (active) space contractions."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cav()
        self.Fca  = w.utils.gen_op("f", 1, "ca",  "ca")
        self.Vca  = w.utils.gen_op("v", 2, "ca",  "ca")
        self.T1   = w.utils.gen_op("t", 1, "av",  "ca", diagonal=False)
        self.T2   = w.utils.gen_op("t", 2, "av",  "ca", diagonal=False)
        self.T4   = w.utils.gen_op("t", 4, "av",  "ca", diagonal=False)
        # specific single-component operators with active indices
        self.v_caav    = w.op("v", ["v+ a+ c a"])
        self.v_aavv    = w.op("v", ["v+ v+ a a"])
        self.t2_ccav   = w.op("t", ["v+ a+ c c"])
        self.t2_aaav   = w.op("t", ["v+ v+ a a"])
        self.t4_cccav  = w.op("t", ["v+ v+ v+ a+ c c c c"])
        self.t4_ccaavv = w.op("t", ["v+ v+ a+ a+ c c a a"])

    def _check(self, name, expr):
        assert contract(expr) == load_ref(name)

    def test_Fca_T1(self):     self._check("cav_Fca_T1",  self.Fca@self.T1)
    def test_Fca_T2(self):     self._check("cav_Fca_T2",  self.Fca@self.T2)
    def test_Fca_T4(self):     self._check("cav_Fca_T4",  self.Fca@self.T4)
    def test_Vca_T1_T1(self):  self._check("cav_Vca_T1_T1", self.Vca@self.T1@self.T1)
    def test_Vca_T2_T1(self):  self._check("cav_Vca_T2_T1", self.Vca@self.T2@self.T1)
    def test_Vca_T4(self):     self._check("cav_Vca_T4",     self.Vca@self.T4)

    def test_vcaav_t2ca_t2ca(self):
        self._check("cav_vcaav_t2ca_t2ca",
                    self.v_caav @ self.t2_ccav @ self.t2_ccav)

    def test_vaavv_t2aa_t2aa(self):
        self._check("cav_vaavv_t2aa_t2aa",
                    self.v_aavv @ self.t2_aaav @ self.t2_aaav)

    def test_vcaav_t4cccav_t2ca(self):
        self._check("cav_vcaav_t4cccav_t2ca",
                    self.v_caav @ self.t4_cccav @ self.t2_ccav)

    def test_vcaav_t4ccaavv_t2ca(self):
        self._check("cav_vcaav_t4ccaavv_t2ca",
                    self.v_caav @ self.t4_ccaavv @ self.t2_ccav)

    def test_vcaav_t4ccaavv_t2ca_t2ca(self):
        self._check("cav_vcaav_t4ccaavv_t2ca_t2ca",
                    self.v_caav @ self.t4_ccaavv @ self.t2_ccav @ self.t2_ccav)


class TestRegressionCABV:
    """Four-space (core/active-a/active-b/virtual) — two general spaces."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cabv()
        self.v4_ccab  = w.op("v", ["a+ b+ c c"])
        self.v4_cabv  = w.op("v", ["v+ b+ c a"])
        self.v4_aavv  = w.op("v", ["v+ v+ a a"])
        self.v4_abvv  = w.op("v", ["v+ v+ a b"])
        self.t2_4a    = w.op("t", ["v+ a+ c c"])
        self.t2_4b    = w.op("t", ["v+ b+ c c"])
        self.t2_4ab   = w.op("t", ["v+ v+ a b"])
        self.t3_4a    = w.op("t", ["v+ v+ a+ c c c"])
        self.t4_4     = w.op("t", ["v+ v+ v+ v+ c c c c"])
        self.t4_4ab   = w.op("t", ["v+ v+ a+ b+ c c a b"])
        self.t4_4mix  = w.op("t", ["v+ v+ v+ a+ c c c c"])

    def _check(self, name, expr):
        assert contract(expr) == load_ref(name)

    def test_vcabv_t2a_t2b(self):
        self._check("cabv_vcabv_t2a_t2b",
                    self.v4_cabv @ self.t2_4a @ self.t2_4b)

    def test_vccab_t4ab_t2a(self):
        self._check("cabv_vccab_t4ab_t2a",
                    self.v4_ccab @ self.t4_4ab @ self.t2_4a)

    def test_vcabv_t4mix_t2a(self):
        self._check("cabv_vcabv_t4mix_t2a",
                    self.v4_cabv @ self.t4_4mix @ self.t2_4a)

    def test_vabvv_t2ab_t2ab(self):
        self._check("cabv_vabvv_t2ab_t2ab",
                    self.v4_abvv @ self.t2_4ab @ self.t2_4ab)

    def test_vccab_t3a_t3a(self):
        self._check("cabv_vccab_t3a_t3a",
                    self.v4_ccab @ self.t3_4a @ self.t3_4a)

    def test_vaavv_t2ab_t2ab(self):
        self._check("cabv_vaavv_t2ab_t2ab",
                    self.v4_aavv @ self.t2_4ab @ self.t2_4ab)

    def test_vcabv_t4ab_t2a_t2b(self):
        self._check("cabv_vcabv_t4ab_t2a_t2b",
                    self.v4_cabv @ self.t4_4ab @ self.t2_4a @ self.t2_4b)


# ── Layer 2: mathematical invariants ─────────────────────────────────────────

class TestInvariantsOV:
    """Invariants that must hold regardless of canonicalization implementation."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_ov()

    def test_canon_reduces_or_preserves_term_count(self):
        """Canonicalization must never produce more terms than without it."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        T3 = w.op("t", ["v+ v+ v+ o o o"])
        T4 = w.op("t", ["v+ v+ v+ v+ o o o o"])
        for expr in [V@T2@T2, V@T3@T3, V@T4@T4, V@T3@T3@T2, V@T4@T2@T2]:
            n_on  = len(contract(expr, canon=True))
            n_off = len(contract(expr, canon=False))
            assert n_on <= n_off, (
                f"canon=True gave {n_on} terms but canon=False gave {n_off}"
            )

    def test_identical_operators_canon_never_adds_terms(self):
        """Canonicalization must never produce more terms than without it,
        even for products with repeated identical operators."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        T3 = w.op("t", ["v+ v+ v+ o o o"])
        T4 = w.op("t", ["v+ v+ v+ v+ o o o o"])
        for expr in [V@T2@T2, V@T3@T3, V@T4@T4]:
            n_on  = len(contract(expr, canon=True))
            n_off = len(contract(expr, canon=False))
            assert n_on <= n_off, (
                f"canon=True gave {n_on} terms but canon=False gave {n_off}"
            )

    def test_canon_off_terms_sum_to_canon_on(self):
        """Every canonical term's coefficient must equal the sum of the
        coefficients of all corresponding terms in the no-canon result.

        Both results go through term.canonicalize(), so tensor-structure
        strings are comparable.  We collect coefficients by term string and
        verify the two maps are equal.
        """
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        T3 = w.op("t", ["v+ v+ v+ o o o"])
        for expr in [V@T2, V@T3, V@T2@T2, V@T3@T3]:
            expr_on  = contract(expr, canon=True)
            expr_off = contract(expr, canon=False)
            # build coefficient maps keyed on string representation of each term
            map_on  = {str(t): c for t, c in expr_on}
            map_off: dict = collections.defaultdict(lambda: w.rational(0))
            for t, c in expr_off:
                map_off[str(t)] += c
            assert map_on == dict(map_off), (
                "canon=True and canon=False disagree on coefficients"
            )

    def test_empty_contraction_range_gives_empty_expression(self):
        """Contracting with minrank > maxrank must always return empty."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), V@T2, 10, 8)
        assert result == w.Expression()


class TestInvariantsCAV:
    """Invariants for the three-space (core/active/virtual) setup."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cav()

    def test_canon_reduces_or_preserves_term_count(self):
        Vca = w.utils.gen_op("v", 2, "ca", "ca")
        T1  = w.utils.gen_op("t", 1, "av", "ca", diagonal=False)
        T2  = w.utils.gen_op("t", 2, "av", "ca", diagonal=False)
        for expr in [Vca@T1@T1, Vca@T2@T1]:
            n_on  = len(contract(expr, canon=True))
            n_off = len(contract(expr, canon=False))
            assert n_on <= n_off

    def test_active_space_contractions_with_four_body(self):
        """Four-body operators spanning the active space must produce
        the correct expression with the active-space (general) contraction rules."""
        v_caav    = w.op("v", ["v+ a+ c a"])
        t4_ccaavv = w.op("t", ["v+ v+ a+ a+ c c a a"])
        t2_ccav   = w.op("t", ["v+ a+ c c"])
        result = contract(v_caav @ t4_ccaavv @ t2_ccav)
        assert result == load_ref("cav_vcaav_t4ccaavv_t2ca")


class TestInvariantsCABV:
    """Invariants for the four-space (core/active-a/active-b/virtual) setup."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cabv()

    def test_canon_reduces_or_preserves_term_count(self):
        v4_cabv = w.op("v", ["v+ b+ c a"])
        t2_4a   = w.op("t", ["v+ a+ c c"])
        t2_4b   = w.op("t", ["v+ b+ c c"])
        t4_4ab  = w.op("t", ["v+ v+ a+ b+ c c a b"])
        for expr in [v4_cabv@t2_4a@t2_4b,
                     v4_cabv@t4_4ab@t2_4a@t2_4b]:
            n_on  = len(contract(expr, canon=True))
            n_off = len(contract(expr, canon=False))
            assert n_on <= n_off

    def test_two_general_spaces_distinct(self):
        """Operators in space 'a' and space 'b' must not be identified.
        A contraction that only closes within 'a' must differ from one
        that closes within 'b'."""
        v4_aavv  = w.op("v", ["v+ v+ a a"])
        v4_bbvv  = w.op("v", ["v+ v+ b b"])
        t2_4ab   = w.op("t", ["v+ v+ a b"])
        r_a = contract(v4_aavv @ t2_4ab @ t2_4ab)
        r_b = contract(v4_bbvv @ t2_4ab @ t2_4ab)
        assert r_a != r_b


# ── Layer 3: edge cases that stress-test canonicalize_contraction_graph ───────

class TestEdgeCasesOV:
    """Edge cases for the two-space (occupied/virtual) setup."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_ov()

    # ── rank constraints ───────────────────────────────────────────────────────

    def test_rank_zero_terms_are_fully_contracted(self):
        """Contracting to rank 0 must yield only scalar (fully contracted) terms."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), V@T2, 0, 0)
        assert len(result) > 0, "V@T2 rank-0 contraction should be non-empty"
        for term, _ in result:
            s = str(term)
            assert "a+" not in s and "a-" not in s, (
                f"rank-0 term still has free SQ operators: {s}"
            )

    def test_rank_filter_strictly_reduces_terms(self):
        """Restricting maxrank must give at most as many terms as the full contraction."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        wt_full = w.WickTheorem(); wt_full.set_single_threaded(True)
        wt_r2   = w.WickTheorem(); wt_r2.set_single_threaded(True)
        full = wt_full.contract(w.rational(1), V@T2, 0, 999)
        r2   = wt_r2.contract(w.rational(1), V@T2,   0, 2)
        assert len(r2) <= len(full)

    def test_rank_one_result_contains_only_one_body_operators(self):
        """Contracting to rank 1 must yield only 1-body residual terms."""
        F  = w.utils.gen_op("f", 1, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), F@T2, 1, 1)
        for term, _ in result:
            s = str(term)
            n_cre = s.count("a+(")
            n_ann = s.count("a-(")
            assert n_cre == 1 and n_ann == 1, (
                f"rank-1 term has wrong operator count: cre={n_cre} ann={n_ann}"
            )

    # ── determinism ───────────────────────────────────────────────────────────

    def test_canon_is_deterministic(self):
        """Contracting the same expression twice must return equal results."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T3 = w.op("t", ["v+ v+ v+ o o o"])
        result1 = contract(V@T3@T3, canon=True)
        result2 = contract(V@T3@T3, canon=True)
        assert result1 == result2

    def test_nocanon_is_deterministic(self):
        """No-canon mode must also be deterministic."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T3 = w.op("t", ["v+ v+ v+ o o o"])
        result1 = contract(V@T3@T3, canon=False)
        result2 = contract(V@T3@T3, canon=False)
        assert result1 == result2

    # ── one-body simplicity ───────────────────────────────────────────────────

    def test_one_body_canon_equals_nocanon(self):
        """For a single one-body operator product, graph canonicalization
        cannot change the physical content: canon=ON and canon=OFF should
        give the same expression (only one operator permutation is possible)."""
        F  = w.utils.gen_op("f", 1, "ov", "ov")
        T1 = w.op("t", ["v+ o"])
        r_on  = contract(F@T1, canon=True)
        r_off = contract(F@T1, canon=False)
        assert r_on == r_off

    # ── non-contracting cases ─────────────────────────────────────────────────

    def test_no_rank_zero_for_unmatched_operators(self):
        """An expression that cannot produce a vacuum expectation value
        should have no rank-0 terms (particle-number non-conserving)."""
        T1 = w.op("t", ["v+ o"])   # only creation-type in SQ sense
        T2 = w.op("t", ["v+ v+ o o"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), T1@T2, 0, 0)
        assert len(result) == 0

    # ── coefficient consistency ───────────────────────────────────────────────

    def test_canon_on_total_coeff_equals_nocanon_total_for_one_body(self):
        """For the simplest case F@T1 contracted to rank 0, the sum of
        coefficients must agree between canon=ON and canon=OFF."""
        F  = w.utils.gen_op("f", 1, "ov", "ov")
        T1 = w.op("t", ["v+ o"])
        wt_on  = w.WickTheorem(); wt_on.set_single_threaded(True)
        wt_off = w.WickTheorem(); wt_off.set_single_threaded(True)
        wt_off.do_canonicalize_graph(False)
        r_on  = wt_on.contract(w.rational(1),  F@T1, 0, 0)
        r_off = wt_off.contract(w.rational(1), F@T1, 0, 0)
        # sum all coefficients
        def total(expr):
            s = w.rational(0)
            for _, c in expr:
                s = s + c
            return s
        assert total(r_on) == total(r_off)

    # ── sign tests ────────────────────────────────────────────────────────────

    def test_four_body_sign_stability(self):
        """T4 contracted with itself must have the same fermion sign
        structure regardless of canonicalization."""
        T4 = w.op("t", ["v+ v+ v+ v+ o o o o"])
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        # The expression is well-defined; verify canon/no-canon term counts match
        r_on  = contract(V@T4, canon=True)
        r_off = contract(V@T4, canon=False)
        assert len(r_on) <= len(r_off)
        assert len(r_on) > 0

    # ── high-symmetry: many identical operators ────────────────────────────────

    def test_triple_identical_operators(self):
        """V@T2@T2@T2: three identical T2 operators — maximum permutation
        degeneracy.  Canonicalization must reduce or preserve term count."""
        V  = w.utils.gen_op("v", 2, "ov", "ov")
        T2 = w.op("t", ["v+ v+ o o"])
        n_on  = len(contract(V@T2@T2@T2, canon=True))
        n_off = len(contract(V@T2@T2@T2, canon=False))
        assert n_on <= n_off
        assert n_on > 0


class TestEdgeCasesCAV:
    """Edge cases for the three-space (core/active/virtual) setup."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cav()

    def test_active_space_rank_zero_is_non_empty(self):
        """A product that can produce active-space cumulants at rank 0
        should yield a non-empty rank-0 expression (Fca@T1 → η₁ scalar)."""
        Fca = w.utils.gen_op("f", 1, "ca", "ca")
        T1  = w.utils.gen_op("t", 1, "av", "ca", diagonal=False)
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), Fca@T1, 0, 0)
        assert len(result) > 0

    def test_active_one_body_canon_equals_nocanon(self):
        """For a single c/a/v one-body product, canon and no-canon agree."""
        Fca = w.utils.gen_op("f", 1, "ca", "ca")
        T1  = w.utils.gen_op("t", 1, "av", "ca", diagonal=False)
        r_on  = contract(Fca@T1, canon=True)
        r_off = contract(Fca@T1, canon=False)
        assert r_on == r_off

    def test_rank_zero_cumulant_terms_fully_contracted(self):
        """All rank-0 terms in an active-space contraction must be fully contracted."""
        v_caav   = w.op("v", ["v+ a+ c a"])
        t2_ccav  = w.op("t", ["v+ a+ c c"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), v_caav@t2_ccav, 0, 0)
        for term, _ in result:
            s = str(term)
            assert "a+" not in s and "a-" not in s

    def test_active_space_identity_contraction(self):
        """Contracting an operator with its own components in a symmetric way
        must give a non-negative term count with canonicalization."""
        t2_ccav = w.op("t", ["v+ a+ c c"])
        n_on  = len(contract(t2_ccav@t2_ccav, canon=True))
        n_off = len(contract(t2_ccav@t2_ccav, canon=False))
        assert n_on <= n_off

    def test_canon_deterministic_with_active_cumulants(self):
        """Repeated contraction with active-space cumulants must be deterministic."""
        v_caav    = w.op("v", ["v+ a+ c a"])
        t4_ccaavv = w.op("t", ["v+ v+ a+ a+ c c a a"])
        t2_ccav   = w.op("t", ["v+ a+ c c"])
        r1 = contract(v_caav@t4_ccaavv@t2_ccav, canon=True)
        r2 = contract(v_caav@t4_ccaavv@t2_ccav, canon=True)
        assert r1 == r2


class TestEdgeCasesCABV:
    """Edge cases for the four-space (core/active-a/active-b/virtual) setup."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        setup_cabv()

    def test_all_spaces_contraction_non_empty(self):
        """An operator product that involves all four spaces must produce
        a non-empty contracted expression."""
        v4_cabv = w.op("v", ["v+ b+ c a"])
        t2_4a   = w.op("t", ["v+ a+ c c"])
        t2_4b   = w.op("t", ["v+ b+ c c"])
        result = contract(v4_cabv@t2_4a@t2_4b)
        assert len(result) > 0

    def test_space_a_and_b_give_different_expressions(self):
        """Contracting operators that span only 'a' space must produce a
        different expression from operators that span only 'b' space."""
        t2_4a  = w.op("t", ["v+ a+ c c"])
        t2_4b  = w.op("t", ["v+ b+ c c"])
        v_ccaa = w.op("v", ["a+ a+ c c"])
        v_ccbb = w.op("v", ["b+ b+ c c"])
        r_a = contract(v_ccaa@t2_4a@t2_4a)
        r_b = contract(v_ccbb@t2_4b@t2_4b)
        # both should be non-empty and different (distinct density matrices)
        assert len(r_a) > 0 and len(r_b) > 0
        assert r_a != r_b

    def test_canon_deterministic_four_space(self):
        """Four-space contractions must be reproducible."""
        v4_ccab = w.op("v", ["a+ b+ c c"])
        t3_4a   = w.op("t", ["v+ v+ a+ c c c"])
        r1 = contract(v4_ccab@t3_4a@t3_4a, canon=True)
        r2 = contract(v4_ccab@t3_4a@t3_4a, canon=True)
        assert r1 == r2

    def test_rank_zero_four_space_fully_contracted(self):
        """Rank-0 terms in four-space contractions must have no free operators."""
        v4_cabv = w.op("v", ["v+ b+ c a"])
        t2_4a   = w.op("t", ["v+ a+ c c"])
        t2_4b   = w.op("t", ["v+ b+ c c"])
        wt = w.WickTheorem(); wt.set_single_threaded(True)
        result = wt.contract(w.rational(1), v4_cabv@t2_4a@t2_4b, 0, 0)
        for term, _ in result:
            s = str(term)
            assert "a+" not in s and "a-" not in s

    def test_a_space_and_b_space_cumulants_differ(self):
        """The density cumulant tensors for space 'a' and space 'b' must be
        recognised as distinct objects.  Contracting a Fock-like operator
        through space 'a' must give a different symbolic result than through
        space 'b'."""
        Fca = w.utils.gen_op("f", 1, "ca", "ca")
        Fcb = w.utils.gen_op("f", 1, "cb", "cb")
        T1a = w.utils.gen_op("t", 1, "av", "ca", diagonal=False)
        T1b = w.utils.gen_op("t", 1, "bv", "cb", diagonal=False)
        r_a = contract(Fca@T1a)
        r_b = contract(Fcb@T1b)
        assert len(r_a) > 0 and len(r_b) > 0
        assert r_a != r_b

